### PR TITLE
add the NBIS training events to the BioSchemas scraper sources

### PR DESCRIPTION
**Pull request by mihai-sysbio**
This PR is meant to stay in `draft` mode until the `json` gets updated according to BioSchemas.

_edit: it might take a few days until the referenced JSON is made public - please reach out if it takes too long_

### CODE REVIEW

**Comment by fbacall** [comment]
Hi, I tried this out but the JSON did not seem to contain any Bioschemas/schema.org.

I also checked out some of the links that were linked from the JSON and also could not find any Bioschemas on the pages. Is this the correct URL?

**Comment by mihai-sysbio** [comment]
@fbacall sorry for not being clear: a json already existed at that URL, but it's the old one. Please see the updated json attached here: 
[courses.json.txt](https://github.com/ElixirTeSS/bioschemas_sources/files/9928177/courses.json.txt)

_edit: I shared the wrong json initially_

**Comment by fbacall** [comment]
That's the JSON I was looking at.

For reference, bioschemas JSON would look something like this:
```json
[
  {
    "@context": "https://schema.org",
    "@type": "Course",
    "name": "CAS Personalized Molecular Oncology",
    "description": "# [More information on the CAS of Personalized Molecular Oncology website](https://advancedstudies.unibas.ch/courses/course/cas-personalized-molecular-oncology-191983)",
    "inLanguage": "en-GB",
    "provider": {
      "@type": "Organization",
      "name": "SIB Swiss Institute of Bioinformatics",
      "@id": "https://ror.org/002n09z45"
    },
    "abstract": null,
    "educationalLevel": "Intermediate",
    "http://purl.org/dc/terms/conformsTo": {
      "@id": "https://bioschemas.org/profiles/Course/1.0-RELEASE",
      "@type": "CreativeWork"
    },
    "hasCourseInstance": [
      {
        "@type": "CourseInstance",
        "name": "CAS Personalized Molecular Oncology",
        "description": "# [More information on the CAS of Personalized Molecular Oncology website](https://advancedstudies.unibas.ch/courses/course/cas-personalized-molecular-oncology-191983)",
        "url": "https://www.sib.swiss/training/course/20221101_CASPM",
        "@id": "https://www.sib.swiss/training/course/20221101_CASPM",
        "http://purl.org/dc/terms/conformsTo": {
          "@id": "https://bioschemas.org/profiles/CourseInstance/1.0-RELEASE",
          "@type": "CreativeWork"
        },
        "about": [
          {
            "@type": "Event",
            "name": "CAS Personalized Molecular Oncology"
          }
        ],
        "courseMode": [
          "onsite",
          "synchronous"
        ],
        "keywords": "",
        "location": "Basel",
        "endDate": "2023-10-31",
        "inLanguage": "en-GB",
        "instructor": [],
        "organizer": [
          {
            "@type": "Person",
            "name": "Patricia Palagi"
          },
          {
            "@type": "Organization",
            "@id": "https://ror.org/002n09z45",
            "name": "SIB Swiss Institute of Bioinformatics"
          }
        ],
        "offers": [
          {
            "@type": "Offer",
            "name": "Academic Price",
            "price": 6000,
            "eligibleCustomerType": {
              "@type": "BusinessEntityType",
              "name": "Academic"
            },
            "priceCurrency": "CHF"
          },
          {
            "@type": "Offer",
            "name": "Industry Price",
            "price": 6000,
            "priceCurrency": "CHF",
            "eligibleCustomerType": {
              "@type": "BusinessEntityType",
              "name": "Industrial"
            }
          }
        ],
        "startDate": "2022-11-01"
      }
    ]
  }
  ...
]
```

**Comment by mihai-sysbio** [comment]
I shared the wrong json initially - could you please look at the updated one (above)?

**Comment by fbacall** [comment]
Yep, that works!

Can you let me know when it is available at https://nbis.se/assets/training/courses.json ?

Then I can merge this.

**Comment by mihai-sysbio** [comment]
@fbacall it's live now

**Comment by mihai-sysbio** [comment]
@fbacall I'm following up on this PR since no updates seem to have propagated to TeSS - any clue what might be going on?

**Comment by fbacall** [comment]
Good catch, we moved TeSS onto a new server recently and it seems the scrapers were not running correctly.

I re-ran it and the updates should be there now.

**Comment by mihai-sysbio** [comment]
Many thanks @fbacall, I can confirm all looks great 🎉

**Pull request merged**
